# Generated by Django 3.2.5 on 2021-07-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=3)),
                ('wage', models.FloatField()),
            ],
        ),
    ]
