# Generated by Django 3.2.5 on 2021-07-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ix', models.DateTimeField()),
                ('series_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
        ),
    ]
