# Generated by Django 3.2.5 on 2021-07-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_longtimeseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='PivotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_col_a', models.CharField(max_length=15)),
                ('row_col_b', models.CharField(max_length=15)),
                ('row_col_c', models.CharField(max_length=15)),
                ('value_col_d', models.FloatField()),
                ('value_col_e', models.FloatField()),
                ('value_col_f', models.FloatField()),
            ],
        ),
    ]
